### ISSUE TITLE
Unable to run wine

### ISSUE THREAD

**Issue by jshridha** [suchja/wine#1]
I am trying to run the wine initialization using both tags (suchja/wine:latest and suchja/wine:dev1.7.38).

Using the latest, I get the error:

```
/usr/bin/wine32: 1: /usr/bin/wine32: Syntax error: "(" unexpected
```

When running the development version, I get the error:

```
bash: /usr/bin/wine: cannot execute binary file: Exec format error
```

I suspect this is a 32 vs 64 bit error. I'm not sure why this would happen since my host is a 64 bit operating system. Any help would be appreciated! Thanks.

**Comment by suchja** [comment]
I'll have a look into it. Just one quick question. Which version of Docker are you running?

**Comment by jshridha** [comment]
Here's the output from docker -v:

```
Docker version 1.6.2, build 7c8fca2
```

Thanks for taking the time to look into this.

**Comment by suchja** [comment]
Actually I'm not clear on how you are using the image and when/where you get the error. Could you please paste the command you are using to start the container here? Also what did you do to get the error as indicated above?
Sorry for this back and forth, but we will get your problem fixed soon.

**Comment by jshridha** [comment]
No problem. I'm sorry I didn't give more information about my steps. I basically followed the readme and ran these commands in order:

```
docker run -d --name display -e VNC_PASSWORD=newPW -p 5900:5900 suchja/x11server
docker run --rm -it --link display:xserver --volumes-from display suchja/wine:latest /bin/bash
```

Then from inside the container, I ran:

```
wine wineboot --init
```

This followed with the error messages in my original post. I changed the image to suchja/wine:dev1.7.38 in order to see if that version would work:

```
docker run --rm -it --link display:xserver --volumes-from display suchja/wine:dev1.7.38 /bin/bash
```

and again got the error message in the first post.

**Comment by suchja** [comment]
Finally I was able to check it on my System again. Currently I'm running Docker 1.6.0 with Boot2Docker 1.6.0 on a Mac. When running the above commands (copy & paste from your comment), everything runs smoothly. I do get the `X error ...` as indicated in the README.md, but otherwise everything is okay.

Do you have the latest version of the image from Docker hub, or did you build it yourself?

Actually this shouldn't be any problem with 32 / 64 bit. Wine currently supports only 32 bit. There is some experimental 64 bit development happening, but this is not officially released. So basically all docker containers running a 32 bit wine on a 64 bit host without any problems.

I'll do an update of my docker installation to 1.7.1 pretty soon (maybe today). I'll then check it again and see whether this changes anything. I'll also check again the wine documentation what other logs exist we might find some additional information about your problem.

While updating my images from docker hub I experienced an issue, which you might have as well, when you are using Boot2Docker or any other solution with a VM. The virtual hard disk of Boot2Docker is set to 18.2GB. When it is full, I already experienced very different strange problems. Maybe you check on this. See more details [here](http://blog.benhall.me.uk/2015/01/boot2docker-runs-disk-space/).

**Comment by jshridha** [comment]
My setup is running docker on a slackware (unraid) machine with a 30 GB btrfs image. It looks like I have plenty of free space. Just to be sure I created a new btrfs image, which wipes the slate clean, and the results are the same.

Yes, I have the latest image from Docker hub. I'll try building it myself to see if any errors show themselves during the build process.

I tried it yesterday with Kitematic (which uses boot2docker) on my Windows machine and everything went fine. My guess is there's something on my linux machine that is interfering, but I can't imagine what that could be.

**Comment by suchja** [comment]
I've never tried it on anything else than boot2docker. However, the image has now nearly 250 downloads. Thus I expected that at least somebody has tried it on Linux. Maybe boot2docker has some special setup.

You could try running such/wine without x11server. Thus you also avoid any linking and bind mounting:
`docker run --rm -it --entrypoint /bin/bash suchja/wine:latest`

I'm not that Linux expert so I can't support you there. However, I'll check how to further debug the issue.

**Comment by jshridha** [comment]
I tried that docker run command as well and have the same problem. I delved deeper into the /usr/bin/wine script and it eventually points to /usr/lib/i386-linux-gnu/wine/bin/wine

If I try to run this binary directly instead of through the /usr/bin/wine script, I get the error: 

```
bash: ./wine: cannot execute binary file: Exec format error
```

Since docker containers run on the host's Kernel, my guess is that my Kernels has something disabled that wine is trying to use.

Progress: I just installed wine on my host OS. I get the same exec error when running wine32 but wine64 runs without a problem. Can you include wine64 in your docker image with the required libraries?

**Comment by suchja** [comment]
Let me think about that. Initially I did not include it, because it adds quite some overhead. The image is already pretty large. Maybe its time to add another tag for that.

Is wine64 running smoothly anyway?

**Comment by jshridha** [comment]
I think I may have found another solution. It looks like wine64 is included
in the dev version. I had to modify the winegui bashrc command to point to
wine64 and am trying it out. I'll report back when it's fully baked.

**Comment by jshridha** [comment]
Everything seems to be working great now with wine64 and the dev version.

I'm probably going to fork your x11server, x11client, and wine dev versions
to create one docker to host a windows application that I've wanted to
containerize for a while. It's the last VM that I have yet migrate over to
a docker.

Thanks a lot for all your help! I'll be keeping an eye on your dockers for
updates! Great work!

**Comment by suchja** [comment]
One thing you might consider, if you still want to use wine32, enable debug messages from wine. In the dockerfile I suppress them by `ENV WINEDEBUG -all`, but there are tons of different switches. In the Dockerfile you will find a link to winehq where you can find more details.

I'll close this issue now. In case you have further question we can open it again.

Glad to know the work helped somebody else as well!
