### ISSUE TITLE
Getting error if executing WINE in multiple sessions

### ISSUE THREAD

**Issue by wernight** [suchja/wine#7]
In a Dockerfile, doing works:

```
RUN wine msiexec -i /tmp/python.msi -quiet -qn -norestart \
   && wine c:/Python27/python.exe C:/Python27/Lib/site-packages/pywin32_postinstall.py -quiet -install
```

This does not:

```
RUN wine msiexec -i /tmp/python.msi -quiet -qn -norestart
RUN wine c:/Python27/python.exe C:/Python27/Lib/site-packages/pywin32_postinstall.py -quiet -install
```

The later gives:

```
  File "C:\Python27\lib\random.py", line 113, in seed
    a = long(_hexlify(_urandom(2500)), 16)
WindowsError: [Error -2146893801] Windows Error 0x80090017
```

Independent almost of the commands executed above, it looks like running wine within a single bash session works, but doing multiple `RUN` calling `wine` fails.

This is pretty important for people trying extend for example to automate some Windows programs during CI.

**Comment by suchja** [comment]
Totally agree! This drove me crazy as well! Problem is that wine as multi-process application is difficult to handle in a Dockerfile. Please see the paragraph starting with “ATTENTION:” in the section “Usage” in the readme-file: https://github.com/suchja/wine#usage https://github.com/suchja/wine#usage

I had a longer discussion with the guys from docker several months ago. However, it seems this problem is more or less specific to wine in a container. So at that time there was no better way to handle it. See this issue https://github.com/docker/docker/issues/12795 https://github.com/docker/docker/issues/12795 and especially this pull request https://github.com/docker/docker/pull/12911 https://github.com/docker/docker/pull/12911 for additional details.

**Comment by wernight** [comment]
Sounds like it's related to daemon/forked process. Could it be a PID 1 zombie reap related? May be using **phusion/baseimage-docker** base image would solve that, or removing some files locally on bash start so that it the daemon is re-created.

**Comment by suchja** [comment]
Sorry for not coming back on this. Probably it is not longer relevant for you so I'll close this issue.

**Comment by wernight** [comment]
Please re-open it's still not fixed. Example of `Dockerfile`:

```
FROM suchja/wine:latest

WORKDIR /tmp

# Downloads prerequisits.
RUN set -x \
    # https://www.python.org/ftp/python/
 && curl -o python.msi -L https://www.python.org/ftp/python/2.7.14/python-2.7.14.msi \
    # https://sourceforge.net/projects/pywin32/files/pywin32/
 && curl -o pywin32.exe -L 'https://downloads.sourceforge.net/project/pywin32/pywin32/Build%20221/pywin32-221.win32-py2.7.exe?r=&ts=1514898586&use_mirror=kent' \
 && unzip pywin32.exe || true

RUN set -x \
 && wine msiexec -i python.msi -quiet -qn -norestart \
 && cp -r PLATLIB/* SCRIPTS/* $WINEPREFIX/drive_c/Python27/Lib/site-packages
# Fails if this command is not included in the previous "RUN" statement:
RUN wine c:/Python27/python.exe C:/Python27/Lib/site-packages/pywin32_postinstall.py -quiet -install
```

`sudo docker build --pull .` fails with error:

```
Traceback (most recent call last):
  File "C:/Python27/Lib/site-packages/pywin32_postinstall.py", line 9, in <module>
    import tempfile
  File "C:\Python27\lib\tempfile.py", line 35, in <module>
    from random import Random as _Random
  File "C:\Python27\lib\random.py", line 887, in <module>
    _inst = Random()
  File "C:\Python27\lib\random.py", line 97, in __init__
    self.seed(x)
  File "C:\Python27\lib\random.py", line 115, in seed
    a = long(_hexlify(_urandom(2500)), 16)
WindowsError: [Error -2146893801] Windows Error 0x80090017
```

**Comment by shaqman** [comment]
I face the same issue, with the exact error above. Are there any progress on this?
